### ISSUE TITLE
find.py is pointing to core plugins and not custom plugins

### ISSUE THREAD

**Issue by Simon-FJ** [GeoLMg/apt-zsh-plugin#2]
https://github.com/GeoLMg/apt-zsh-plugin/blob/2e6086cf1d695bf92bca8d3423fb635606e5c637/apt.plugin.zsh#L25

git clone https://github.com/GeoLMg/apt-zsh-plugin.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/apt

The git clone for custom plugins will install to $ZSH/custom/plugins/apt/find.py not $ZSH/plugins/apt/find.py

**Comment by GeoLMg** [comment]
Yes, you're right. I had fixed it in the README. Thanks!:)
